### ISSUE TITLE
Use splash image

### ISSUE THREAD

**Issue by RopoMen** [flowplayer/flowplayer-background#2]
If splash image is configured for the player, background video plugin should use that image as still image for devices which cannot autoplay videos.

Configuring it in this way is not good when you need to make it dynamic (change per video):
```
#background.is-loading {
  background-color: #9cf;
  background-image: url(//cdn.flowplayer.org/202777/210503-snap.jpg);
}
```

Also using already existing way makes documentation more simple.

**Comment by phloxic** [comment]
? you can just use the poster option if you don't want to use CSS. And `is-loading` would have to be omitted when autoplay is not allowed.

**Comment by RopoMen** [comment]
Good point.

I have single configuration for the Flowplayer initialization and customer can choose between normal init with optional autoplay or background video.

```
var autoplay = !!(video.autoplay || video.background);
var background = !!video.background ? {mask: 'transparent'} : false;

window.flowplayer(fpHandle[0], {
  background: background,
  splash: autoplay ? false : video.thumbnail,
  autoplay: autoplay,
  ratio: (sources[0] ? sources[0].ratio : (16 / 9)),
  keyboard: false,
  embed: false,
  clip: {
    sources: sources
  }
});
```

Splash is not added if autoplay is used, because what I remember that setup wasn't working. But I didn't remember that I could add both splash and poster for the config.
